version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Diretório onde está localizado o pyproject.toml
    schedule:
      interval: "weekly
    open-pull-requests-limit: 20
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
        
  
