version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Diretório onde está localizado o pyproject.toml
    schedule:
      interval: "daily"  # O menor intervalo suportado oficialmente
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
